src/PersonalAccountBundle/Entity/Invoice.php
<?php
/**
 * Created by PhpStorm.
 * User: Potap
 * Date: 27.06.2017
 * Time: 12:10
 */

namespace PersonalAccountBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\UniqueConstraint;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity
 * @ORM\Table(name="invoice", uniqueConstraints={@UniqueConstraint(name="ivoice_unique", columns={"teacher_lesson","to_date"})})
 */

class Invoice
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="TeacherLesson",)
     * @ORM\JoinColumn(name="teacher_lesson", referencedColumnName="id")
     */
    protected  $teacher_lesson;

    /**
     * @ORM\Column(type="date", nullable = true)
     */
    protected  $from_date;

    /**
     * @ORM\Column(type="date")
     */
    protected  $to_date;

    /**
     * @ORM\Column (type="integer", length=100)
     */
    protected  $total;

    /**
     * @ORM\Column (type="integer", length=100)
     */
    protected  $lesson_comission;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $payed;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getTeacherLesson()
    {
        return $this->teacher_lesson;
    }

    /**
     * @param mixed $teacher_lesson
     */
    public function setTeacherLesson($teacher_lesson)
    {
        $this->teacher_lesson = $teacher_lesson;
    }

    /**
     * @return mixed
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * @param mixed $total
     */
    public function setTotal($total)
    {
        $this->total = $total;
    }

    /**
     * @return mixed
     */
    public function getFromDate()
    {
        return $this->from_date;
    }

    /**
     * @param mixed $from_date
     */
    public function setFromDate($from_date)
    {
        $this->from_date = $from_date;
    }

    /**
     * @return mixed
     */
    public function getToDate()
    {
        return $this->to_date;
    }

    /**
     * @param mixed $to_date
     */
    public function setToDate($to_date)
    {
        $this->to_date = $to_date;
    }
    /**
     * @return mixed
     */
    public function getPayed()
    {
        return $this->payed;
    }

    /**
     * @param mixed $payed
     */
    public function setPayed($payed)
    {
        $this->payed = $payed;
    }

    /**
     * @return mixed
     */
    public function getLessonComission()
    {
        return $this->lesson_comission;
    }

    /**
     * @param mixed $lesson_comission
     */
    public function setLessonComission($lesson_comission)
    {
        $this->lesson_comission = $lesson_comission;
    }
}

src/PersonalAccountBundle/Resources/views/Admin/a1.html.twig
{% extends 'PersonalAccountBundle:Admin:base.html.twig' %}
{% block body %}
    <div class="note">
        <div id="rectangle1"></div>
        <span> - Не заполнено</span>
        <div id="rectangle2"></div>
        <span> - Заполнено</span>
    </div>
    <div id="calendar"></div>
{% endblock %}
{% block javascripts %}
    <script>
        var defaults = {
            'showModalOnLoad': false,
            'events_load_url': '{{ events_load_url }}'
        };
        if (defaults.showModalOnLoad) {
            showModal();
        }
        function showModal() {
            $('#pageopen').modal({
                show: true
            });
        };
    </script>
    <script src ="{{ asset('js/attendance.js') }}"></script>
{% endblock %}
{% block stylesheets %}
    <style>
        #rectangle1, #rectangle2 {
            width:30px;
            height:20px;
            display: inline-block;
            vertical-align: middle;
        }
        #rectangle1 {
            background: blue;
        }
        #rectangle2 {
            background: green;
        }
        .note {
            margin: 0 0 20px;
        }
        .note span {
            padding: 10px 10px 10px 0;
        }
    </style>
{% endblock %}

src/PersonalAccountBundle/Resources/views/Admin/allInvoices.html.twig
{% extends 'PersonalAccountBundle:Admin:base.html.twig' %}
{% block body %}
    <h2>Все счета</h2>
    <table id="all_invoices" class="table table-striped table-bordered table-hover">
        <thead class="thead-inverse">
        <tr>
            <th>Предмет</th>
            <th>Начальная дата (год-месяц-день)</th>
            <th>Конечная дата (год-месяц-день)</th>
            <th>Сумма к оплате (руб.)</th>
            <th>Оплата учителю</th>
            <th>Комиссия</th>
            <!--<th>Оплачено</th>-->
        </tr>
        </thead>
        <tbody>
        {% for value in invoices %}
        <tr>
            <td><a href="/invoices/{{ value["i_id"]}}">{{ value["l_title"]}}</a></td>
            <td>{{ value["i_from_date"] ? value["i_from_date"]|date('Y-m-d')}}</td>
            <td>{{ value["i_to_date"]|date('Y-m-d')}}</td>
            <td>{{ value["i_total"]}}</td>
            <td>{{ value["i_total"] - value["i_lesson_comission"] }}</td>
            <td>{{ value["i_lesson_comission"]}}</td>
            <!--<td>{{ value["i_payed"] ? 'да': 'нет'}}</td>-->
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <hr>
    <a href="/invoice_params" class="btn btn-primary">Сформировать новый счет</a>
{% endblock %}
{% block javascripts %}
    <script src ="{{ asset('js/jquery.dataTables.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('#all_invoices').DataTable({
                ordering: true,
                columnDefs : [
                    { type : 'date', targets : [1,2],orderSequence: ["desc", "asc"], }
                ],
            });
        });
    </script>
{% endblock %}
{% block stylesheets %}
    {{ parent() }}

    <link href="{{ asset('/css/jquery.dataTables.min.css') }}" rel="stylesheet">
{% endblock %}

src/PersonalAccountBundle/Resources/views/Admin/attendance.html.twig
{% extends 'PersonalAccountBundle:Admin:base.html.twig' %}
{% block body %}
    <div class="modal fade" tabindex="-1" role="dialog" id="pageopen">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h3 class="modal-title">{{ modal_title }}</h3>
                    <p id="date_caption">{{ date_caption|date('d-m-Y')}}</p>
                    <p id="start_time_caption">{{ start_time|date('H:i') }}</p>
                </div>
                <div class="modal-body">
                    <div class = "table-responsive">

                        <table class="table table-bordered table-hover table-striped table-primary list-table">
                            <thead>
                            <tr class="info">
                                <th>Ученик</th>
                                <th>Присутствие</th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for attendance in attendances %}
                                <tr>
                                    <td>{{ attendance.student }}</td>
                                    <td>{{ attendance.presence ? 'да': '' }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <div id="calendar"></div>
{% endblock %}
{% block javascripts %}
    <script src ="{{ asset('js/attendance.js') }}"></script>
    <script>
        var defaults = {
            'showModalOnLoad': {{ show_modal }},
            'events_load_url': '{{ events_load_url }}',
        };
        if (defaults.showModalOnLoad) {
            showModal();
        }
        function showModal() {
            $('#pageopen').modal({
                show: true
            });
        };


    </script>

{% endblock %}

src/PersonalAccountBundle/Resources/views/Admin/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>{% block title %}Welcome!{% endblock %}</title>
    {% block stylesheets %}{% endblock %}
    <link rel="icon" type="image/x-icon" href="{{ asset('favicon.ico') }}" />
    <link href="{{ asset('/css/bootstrap.css') }}" type="text/css" rel="stylesheet" />
    <link href="{{ asset('/css/main.css') }}" type="text/css" rel="stylesheet" />
    <link href="{{ asset('/css/fullcalendar.min.css') }}" type="text/css" rel="stylesheet"/>
    <link href="{{ asset('/css/jquery.qtip.min.css') }}" type="text/css" rel="stylesheet"/>
    <script src="{{ asset('/js/jquery.js') }}"></script>
    <script src="{{ asset('/js/moment.min.js') }}"></script>
    <script src="{{ asset('/js/jquery.qtip.min.js') }}"></script>
    <script src ="{{ asset('/js/bootstrap.js') }}"></script>
    <script src ="{{ asset('js/fullcalendar.min.js') }}"></script>
    <script src ="{{ asset('js/locale-all.js') }}"></script>

</head>
<body>
<div id="logout" style="text-align: right">
    <a href="{{ logout_path('main') }}">Выйти</a>
</div>
<nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
    <ul id="nav nav-pills nav-stacked flex-column">
        <li class="nav-item"><a href="/students" class="nav-link">Ученики</a></li>
        <li class="nav-item"><a href="/teachers" class="nav-link">Учителя</a></li>
        <li class="nav-item dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Предметы
                <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li><a href="/lesson_categories">Категории</a></li>
                <li><a href="/lessons">Занятия</a></li>
            </ul>
        </li>
        <li class="nav-item"><a href="/groups" class="nav-link">Группы</a></li>
        <li class="nav-item"><a href="/schedule_choose_group" class="nav-link">Расписание</a></li>
        <li class="nav-item"><a href="/attendance_choose_group" class="nav-link">Посещения</a></li>
        <li class="nav-item"><a href="/my_invoices" class="nav-link">Счета</a></li>
    </ul>

</nav>
<div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3 main-content">
{% block body %}

{% endblock %}
</div>
{% block javascripts %}{% endblock %}

</body>
</html>

src/PersonalAccountBundle/Resources/views/Admin/event.html.twig
{% extends 'PersonalAccountBundle:Admin:base.html.twig' %}
{% block body %}
    <div class="modal fade" tabindex="-1" role="dialog" id="pageopen">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">{{ modal_title }}</h4>
                </div>
                <div class="modal-body">
                    {{ form_start(form) }}
                        {{ form_row(form.teacher_lesson, {'attr': {'class': 'form-control'}}) }}
                        {{ form_row(form.start_date) }}
                        {{ form_row(form.dow, {'attr': {'class':'form-control'}}) }}
                        {{ form_row(form.start_time) }}
                        {{ form_row(form.end_time) }}
                        {{ form_row(form.description, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="modal-footer">
                    {{ form_widget(form.save, { 'label': 'Сохранить' }) }}
                    {{ form_widget(form.delete, { 'label': 'Удалить' }) }}
                    {{ form_end(form) }}
                    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <div id="calendar"></div>
{% endblock %}
{% block javascripts %}
    <script>
        var defaults = {
            'showModalOnLoad': {{ show_modal }},
            'events_load_url': '{{ events_load_url }}',
        };
        if (defaults.showModalOnLoad) {
            showModal();
        }
        $('#schedule_delete').attr('disabled','disabled');
        function showModal() {
            $('#pageopen').modal({
                show: true
            });
        };
    </script>
    <script src ="{{ asset('js/schedule.js') }}"></script>
{% endblock %}

src/PersonalAccountBundle/Resources/views/Admin/groupChoose.html.twig
{% extends 'PersonalAccountBundle:Admin:base.html.twig' %}
{% block body %}
    <h2>Выберите группу из списка</h2>
    <div class="list-group" >
        {% for value in result %}
            {% if (schedule) %}
                <a class="list-group-item" href="{{value.id}}/add_event">{{ value.name }}</a>
            {% else %}
                <a class="list-group-item" href="{{value.id}}/attendance">{{ value.name }}</a>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}
{% block javascripts %}
    <script>
    $(document).ready(function() {
        $('.list-group-item').click(function(){
            $(this).css({
                color: '#fff',
                background:'#0275d8',
                border: '#0275d8'
            });
    });
    });
    </script>
{% endblock %}

src/PersonalAccountBundle/Resources/views/Admin/groups.html.twig
{% extends 'PersonalAccountBundle:Admin:base.html.twig' %}
{% block body %}
    {% if errors %}
        <div class="alert alert-danger" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
            Выбранные группы не могут быть удалены. Заполните журнал посещений и проверьте счета для уроков:
            <ul>
                {%  for e in errors %}
                    <li>{{ e.teacherLesson.title ~ ', ' ~ e.date|date('d-m-Y')  ~ ', (группа ' ~ e.group.name  ~')' }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <h2>Все группы</h2>
    <table id="all_groups" class="table table-striped table-bordered table-hover">
        <thead class="thead-inverse">
        <tr>
            <th>Название группы</th>
            <th>Список студентов</th>
        </tr>
        </thead>
        <tbody>
        {% for value in result %}
            <tr>
                <td>{{ value.name }}</td>
                <td>
                {% for s in value.students %}
                    {{ s ~ ', ' }}
                {% endfor %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <hr>
    <button class="btn btn-danger" data-toggle="modal" data-target="#FormModal">Удалить</button>
    <!-- Modal -->
    <div class="modal fade" id="FormModal" role="dialog">
        <div class="modal-dialog modal-lrg">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title" id="formModalLabel">Удалить группы</h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {{ form_start(form) }}
                    {{ form_widget(form.group) }}
                    {{ form_widget(form.delete, { 'label': 'Удалить'}) }}
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
    <a class="btn btn-primary" href="/add_group">Добавить</a>
{% endblock %}
{% block javascripts %}
    <script src ="{{ asset('js/jquery.dataTables.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('#all_groups').DataTable({
                ordering: true,
            });
        });
    </script>
{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('/css/jquery.dataTables.min.css') }}" rel="stylesheet">
{% endblock %}

src/PersonalAccountBundle/Resources/views/Admin/invoiceDetails.html.twig
{% extends 'PersonalAccountBundle:Admin:base.html.twig' %}
{% block body %}
<a href="" data-original-title="Edit this user" type="button" class="btn btn-sm btn-warning" data-toggle="modal" data-target="#FormInvoiceModal">
    <i class="glyphicon glyphicon-edit"></i>
</a>
<h3>Счет "{{ invoice_title }}" за период с {{ from_date }} по {{ to_date }}</h3>
<table class="table table-striped table-bordered table-hover ">
    <thead class="thead-inverse">
    <tr>
        <th>Ученик</th>
        <th>Рассчетный период (начало)</th>
        <th>Рассчетный период (конец)</th>
        <th>Сумма к оплате (руб.)</th>
        <th>Комиссия</th>
        <th>Оплата учителю</th>
        <!--<th>Оплачено</th>-->
    </tr>
    </thead>
    <tbody>
    {{ form_start(form) }}
    {% for value in student_invoices %}

        <tr>
            <td>{{ value['s_surname'] }} {{ value['s_name'] }}</td>
            <td>{{ from_date }}</td>
            <td>{{ to_date }}</td>
            <td>{{ value['s_i_total'] }}</td>
            <td>{% set student_comission = (value['s_i_total']/l_rate) * l_comission %}
                {{ student_comission }}</td>
            <td>{{ value['s_i_total'] - student_comission }}</td>
            <!--<td class="paid-view">{{ value['s_i_payed'] ? 'да': 'нет' }}</td>-->
        </tr>
    {% endfor %}
    </tbody>
</table>
    {{ form_widget(form.delete, { 'label': 'Удалить'}) }}
    {{ form_end(form) }}
    <hr>
    <a href="/my_invoices"> << Назад к списку счетов</a>
    <div class="modal fade" tabindex="-1" role="dialog" id="FormInvoiceModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h3 class="modal-title">Редактирование оплаты</h3>
                    <p id="date_caption"></p>
                    <p id="start_time_caption"></p>
                </div>
                <div class="modal-body">
                    <div class = "table-responsive">
                        {{ form_start(form1) }}
                        <table class="table table-bordered table-primary list-table">
                            <thead>
                            <tr class="info">
                                <th>Ученик</th>
                                <th>Сумма к оплате</th>
                                <th>Оплачено</th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for invoice in form1.student_invoice_collection %}
                                <tr>
                                    <td>{{ form_widget (invoice.student_id) }}</td>
                                    <td>{{ form_widget(invoice.total) }}</td>
                                    <td>{{ form_widget(invoice.payed) }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        {{ form_widget(form1.save, { 'label': 'Сохранить' }) }}
                        {{ form_end(form1) }}
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

{% endblock %}

src/PersonalAccountBundle/Resources/views/Admin/invoiceParams.html.twig
{% extends 'PersonalAccountBundle:Admin:base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Формирование счета</div>
                    <div class="panel-body">
                        {{ form_start(form) }}
                        <div class="form_group">
                            <div class="col-md-8 col-md-offset-2">
                                {{ form_row(form.teacher_lesson, {'attr': {'class': 'form-control'}}) }}
                            </div>
                        </div>
                        <div class="form_group">
                            <div class="col-md-8 col-md-offset-2">
                                {{ form_row(form.startDate, {'attr': {'class': 'form-control'}}) }}
                            </div>
                        </div>
                        <div class="form_group">
                            <div class="col-md-8 col-md-offset-2">
                                {{ form_row(form.endDate, {'attr': {'class': 'form-control'}}) }}
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3 col-md-offset-3" style="margin-top:5px;">
                                {{ form_widget(form.make, { 'label': 'Сформировать счет' }) }}
                            </div>
                            <div class="col-md-3" style="margin-top:5px;">
                            <a class="btn btn-large btn-default" href="/my_invoices">Все счета</a>
                            </div>
                        </div>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/PersonalAccountBundle/Resources/views/Admin/lesson.html.twig
{% extends 'PersonalAccountBundle:Admin:base.html.twig' %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    {% if form.delete is defined %}
                        <div class="panel-heading">Редактировать занятие</div>
                    {% else %}
                        <div class="panel-heading">Добавить занятие</div>
                    {% endif %}
                    <div class="panel-body">
                        {{ form_start(form) }}
                        <div class="form_group">
                            <div class="col-md-8 col-md-offset-2">
                                {{ form_row(form.teacher, {'attr': {'class': 'form-control'}}) }}
                            </div>
                        </div>
                        <div class="form_group">
                            <div class="col-md-8 col-md-offset-2">
                                {{ form_row(form.lesson, {'attr': {'class': 'form-control'}}) }}
                            </div>

                        </div>
                        <div class="form_group">
                            <div class="col-md-8 col-md-offset-2">
                                {{ form_row(form.title, {'attr': {'class': 'form-control'}}) }}
                            </div>
                        </div>
                        <div class="form_group">
                            <div class="col-md-8 col-md-offset-2">
                                {{ form_row(form.rate, {'attr': {'class': 'form-control'}}) }}
                            </div>
                        </div>
                        <div class="form_group">
                            <div class="col-md-8 col-md-offset-2">
                                {{ form_row(form.comission, {'attr': {'class': 'form-control'}}) }}
                            </div>
                        </div>
                        <div class="form_group">
                            <div class="col-md-8 col-md-offset-2">
                                {{ form_widget(form.save, { 'label': 'Сохранить' }) }}
                                {% if form.delete is defined  %}
                                {{ form_widget(form.delete, { 'label': 'Удалить' }) }}
                                    {% endif %}
                            </div>
                        </div>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/PersonalAccountBundle/Resources/views/Admin/lessons.html.twig
{% extends 'PersonalAccountBundle:Admin:base.html.twig' %}
{% block body %}
    <h2>Все уроки</h2>
    <table id="all_lessons" class="table table-striped table-bordered table-hover ">
        <thead class="thead-inverse">
        <tr>
            <th>Название курса</th>
            <th>Категория (предмет)</th>
            <th>Учитель</th>
            <th>Тариф</th>
            <th>Комиссия</th>
        </tr>
        </thead>
        <tbody>
        {% for value in result %}
            <tr>
                <td><a href="/lessons/{{ value["tl_id"]}}">{{ value['tl_title'] }}</a></td>
                <td>{{ value['l_name'] }}</td>
                <td>{{ value['t_surname'] ~ ' ' ~ value['t_name'] }}</td>
                <td>{{ value['tl_rate'] }}</td>
                <td>{{ value['tl_comission'] }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <hr>
    <a href="/add_lesson" class="btn btn-primary">Добавить занятие</a>
{% endblock %}
{% block javascripts %}
    <script src ="{{ asset('js/jquery.dataTables.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('#all_lessons').DataTable({
                ordering: true,
            });
        });
    </script>
{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('/css/jquery.dataTables.min.css') }}" rel="stylesheet">
{% endblock %}

src/PersonalAccountBundle/Resources/views/Admin/modal.html.twig
{% extends 'PersonalAccountBundle:Admin:base.html.twig' %}
{% block body %}
    <div class="modal fade" tabindex="-1" role="dialog" id="pageopen">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">{{ modal_title }}</h4>
                </div>
                <div class="modal-body">
                    {{ form_start(form) }}
                    {{ form_row(form.teacher_lesson, {'attr': {'class': 'form-control'}}) }}
                    {{ form_row(form.start_date) }}
                    {{ form_row(form.dow, {'attr': {'class':'form-control'}}) }}
                    {{ form_row(form.start_time) }}
                    {{ form_row(form.end_time) }}
                    {{ form_row(form.description, {'attr': {'class': 'form-control'}}) }}
                </div>
                <div class="modal-footer">
                    {{ form_widget(form.save, { 'label': 'Сохранить' }) }}
                    {{ form_widget(form.delete, { 'label': 'Удалить' }) }}
                    {{ form_end(form) }}
                    <button type="button" class="btn btn-default button-close" data-dismiss="modal">Закрыть</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
{% endblock %}
{% block javascripts %}
    <script>
        var defaults = {
            'showModalOnLoad': {{ show_modal }},
            'events_load_url': '{{ events_load_url }}',
        };
        if (defaults.showModalOnLoad) {
            showModal();
        }
        function showModal() {
            $('#pageopen').modal({
                show: true
            });
        };
        $('.button-close,.modal-header button').click(function () {
            window.location.href = '../add_event';
        })
    </script>
    <script src ="{{ asset('js/schedule.js') }}"></script>
{% endblock %}

src/PersonalAccountBundle/Resources/views/Admin/myInvoices.html.twig
{% extends 'PersonalAccountBundle:Admin:base.html.twig' %}
{% block body %}
    <h2>Все счета</h2>
    <table id="my_invoices" class="table table-striped table-bordered table-hover">
        <thead class="thead-inverse">
        <tr>
            <th>Название</th>
            <th>Начальная дата (год-месяц-день)</th>
            <th>Конечная дата (год-месяц-день)</th>
            <th>Сумма к оплате (руб.)</th>
            <th>Оплата учителям</th>
            <th>Итоговая комиссия</th>
        </tr>
        </thead>
        <tbody>
        {% for value in invoices %}
            <tr>
                <td>
                    <a href="/my_invoices/{{ value["mi_from_date"] ? value["mi_from_date"]|date('Y-m-d'): '0'}}/{{ value["mi_to_date"]|date('Y-m-d')}}">
                        Счета за период c {{ value["mi_from_date"] ? value["mi_from_date"]|date('Y-m-d')}} по
                        {{ value["mi_to_date"]|date('Y-m-d')}}
                    </a>
                </td>
                <td>{{ value["mi_from_date"] ? value["mi_from_date"]|date('Y-m-d')}}</td>
                <td>{{ value["mi_to_date"]|date('Y-m-d')}}</td>
                <td>{{ value["sum_total"]}}</td>
                <td>{{ value["sum_total"] - value["comission_total"] }}</td>
                <td>{{ value["comission_total"]}}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <hr>
    <a href="/invoice_params" class="btn btn-primary">Сформировать новый счет</a>
{% endblock %}
{% block javascripts %}
    <script src ="{{ asset('js/jquery.dataTables.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('#my_invoices').DataTable({
                ordering: true,
                order: [2, "desc" ],
                iDisplayLength: 50,
                columnDefs : [
                    { type : 'date', targets : [1,2],orderSequence: ["desc", "asc"], }
                ],
            });
        });
    </script>
{% endblock %}
{% block stylesheets %}
    {{ parent() }}

    <link href="{{ asset('/css/jquery.dataTables.min.css') }}" rel="stylesheet">
{% endblock %}